
development:
  adapter: postgresql
  encoding: unicode
  database: products_development
  host: localhost
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: products_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: products_production
  pool: 5
  username:
  password:
